platform :ios, '7.0'
workspace 'Workspace.xcworkspace'
source 'http://admin@repo.wingsdk.cn:8082/r/WASdkIntf_CN.git'
source 'http://admin@repo.wingsdk.cn:8082/r/WASdkImpl_CN.git'
source 'http://admin@repo.wingsdk.cn:8082/r/WAApImpl_CN.git'
source 'http://admin@repo.wingsdk.cn:8082/r/WAWebPayImpl_CN.git'
source 'http://admin@repo.wingsdk.cn:8082/r/WAWechatImpl_CN.git'
target "WADemocn" do
pod 'WASdkIntf_CN', '~> 1.1.0'
pod 'WASdkImpl_CN', '~> 1.1.0'
pod 'WAApImpl_CN', '~> 1.1.0'
pod 'WAWebPayImpl_CN', '~> 1.1.0'
pod 'WAWechatImpl_CN', '~> 1.1.0'
end
